name: Jonas A. Schmidt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33648
title: Me myself and I.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#012243'
    - '#dda06a'
    - '#574c50'
    - '#886454'
    - '#b38470'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.8135853798594326
purpose: []
