name: Jonas A. Schmidt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26138
title: Me myself and I
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050409'
    - '#fbc844'
    - '#65534f'
    - '#fefefe'
    - '#a6938c'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
