name: Jonas A. Schmidt
favicon: null
layout_spectrum: 0.88595
typography_spectrum: 0.25164
title: Me myself and I.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#bcb2b0'
    - '#882238'
    - '#e85977'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.8135853798594326
purpose: []
